name: CI - neuro_vgg16

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install numpy pandas matplotlib scikit-learn tensorflow kaggle nbconvert

    - name: Testar imports
      run: |
        python - <<EOF
        import numpy
        import pandas
        import tensorflow
        print("OK")
        EOF

    - name: Executar notebook
      run: |
        jupyter nbconvert --to notebook --execute \
        --ExecutePreprocessor.timeout=300 \
        --ExecutePreprocessor.kernel_name=python3 \
        neuro_vgg16.ipynb
